spring:
  application:
    name: tlias-web-management
    #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#配置mybatis的日志输出
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.IdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javaweb2026
    region: cn-beijing